"""Ingestion pipeline overview: runs the offline knowledge-base flow and persists its deterministic chunk cache."""

import argparse
from dataclasses import asdict
from pathlib import Path
import pickle
from typing import Any

from app.config.config import PROJECT_ROOT
from app.rag.chunking.semantic_chunker import SemanticChunker
from app.rag.loaders.document_loader import DocumentLoader
from app.rag.preprocessing.cleaner import DocumentCleaner
from app.rag.preprocessing.metadata import MetadataParser
from app.rag.app.schemas import Chunk


DEFAULT_KNOWLEDGE_BASE_PATH = PROJECT_ROOT / "knowledge_base"
DEFAULT_CHUNKS_PATH = PROJECT_ROOT / "backend" / "data" / "rag" / "chunks.pkl"
CACHE_SCHEMA_VERSION = 1


class IngestionPipeline:
    """Coordinate loading, cleaning, enrichment, chunking, and cache creation outside request handling."""

    def __init__(self, knowledge_base_path: Path = DEFAULT_KNOWLEDGE_BASE_PATH, chunks_path: Path = DEFAULT_CHUNKS_PATH) -> None:
        self.knowledge_base_path = knowledge_base_path
        self.chunks_path = chunks_path
        self.loader = DocumentLoader()
        self.cleaner = DocumentCleaner()
        self.metadata_parser = MetadataParser()
        self.chunker = SemanticChunker()

    def run(self) -> list[Chunk]:
        """Build chunks from all Markdown knowledge-base files and write the reusable pickle artifact."""
        documents = self.loader.load_directory(self.knowledge_base_path)
        chunks: list[Chunk] = []
        for document in documents:
            cleaned_document = self.cleaner.clean(document)
            enriched_document = self.metadata_parser.enrich(cleaned_document)
            chunks.extend(self.chunker.chunk(enriched_document))
        self.save_chunks(chunks, self.chunks_path)
        return chunks

    @staticmethod
    def save_chunks(chunks: list[Chunk], path: Path) -> None:
        """Persist a versioned cache artifact; callers must never unpickle untrusted files."""
        path.parent.mkdir(parents=True, exist_ok=True)
        payload: dict[str, Any] = {
            "schema_version": CACHE_SCHEMA_VERSION,
            "chunks": [asdict(chunk) for chunk in chunks],
        }
        with path.open("wb") as artifact_file:
            pickle.dump(payload, artifact_file, protocol=pickle.HIGHEST_PROTOCOL)

    @staticmethod
    def load_chunks(path: Path = DEFAULT_CHUNKS_PATH) -> list[Chunk]:
        """Load chunks created by this pipeline; only use artifacts generated by this application."""
        with path.open("rb") as artifact_file:
            payload = pickle.load(artifact_file)
        if payload.get("schema_version") != CACHE_SCHEMA_VERSION:
            raise ValueError("Unsupported chunks cache schema version.")
        return [Chunk(**chunk) for chunk in payload["chunks"]]


def main() -> None:
    """Run ingestion as a command-line job rather than during an API request."""
    parser = argparse.ArgumentParser(description="Build the RAG chunks cache from the knowledge base.")
    parser.add_argument("--knowledge-base", type=Path, default=DEFAULT_KNOWLEDGE_BASE_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_CHUNKS_PATH)
    args = parser.parse_args()
    chunks = IngestionPipeline(args.knowledge_base, args.output).run()
    print(f"Created {len(chunks)} chunks at {args.output}")


if __name__ == "__main__":
    main()
